---
#
# Project:: Ansible Role - SSH Config
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure OpenSSH and the issue.net/motd

- name: Configure OpenSSH
  ansible.builtin.import_tasks: openssh.yml

- name: Configure the login banner
  ansible.builtin.import_tasks: loginbanner.yml
