---
#
# Project:: Ansible Role - SSH Config
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in this role

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
