---
#
# Project:: Ansible Role - CHANGEME
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Handlers used for various tasks in this role

# Handlers for prereqs
- name: CHANGEME
  command: echo "CHANGEME"
